x=float(input("ingresar el primer valor: "))
y=float(input("ingresar el segundo valor: "))
suma=(x+y)
resta=(x-y)
multiplicacion=(x*y)
division=(x/y)
print("la suma es: ", suma)
print("la resta es: ", resta)
print("la multiplicacion es: ", multiplicacion)
print("la division es: ", division)